FirstProject/urls.py
from django.contrib import admin
from django.urls import path,include
from django.conf import settings
from django.contrib.staticfiles.urls import static ,staticfiles_urlpatterns

urlpatterns = [
    path('admin/', admin.site.urls),
    path('',include('firstapp.urls')),
    path('second/',include('secondApp.urls')),
]
urlpatterns +=staticfiles_urlpatterns()
urlpatterns +=static(settings.MEDIA_URL,document_root=settings.MEDIA_ROOT)

firstapp/urls.py
from django.urls import path
from firstapp import views


app_name='firstapp'
urlpatterns = [
    path('',views.IndexView.as_view(),name='home'),
    path('profile/',views.profile,name='profile'),
    path('student_details/<pk>/',views.StudentDetail.as_view(),name='student_details'),
   
]

secondApp/urls.py
from django.urls import path
from secondApp import views


app_name='secondApp'
urlpatterns = [
   
]

firstapp/models.py
from django.db import models

# Create your models here.
class Profile(models.Model):
    GENDER_CHOICES = [
        ('', 'Select a gender'),
        ('Male', 'Male'),
        ('Female', 'Female'),
        ('Others', 'Others'),
    ]
    RELIGION_CHOICES = [
        ('', 'Select a Religion'),
        ('Muslim', 'Muslim'),
        ('Hindu', 'Hindu'),
        ('Buddist', 'Buddist'),
    ]
    name=models.CharField(max_length=30)
    email=models.EmailField(max_length=50)
    phone=models.CharField(max_length=15)
    age=models.PositiveIntegerField()
    image=models.ImageField(upload_to='prof_pic')
    gender =models.CharField(max_length=10, choices=GENDER_CHOICES,default='')
    religion=models.CharField(max_length=10, choices=RELIGION_CHOICES,default='')
    address=models.TextField(max_length=100)

    def __str__(self):
        return self.name

    

secondApp/models.py
from django.db import models

# Create your models here.

firstapp/forms.py
from django import forms
from firstapp.models import Profile

class ProfileForm(forms.ModelForm):
    name=forms.CharField(label="Full Name",required=True)
    email=forms.EmailField(label="Email Address",required=True)
    phone=forms.CharField(label="Phone Number",required=True)
    class Meta:
        model=Profile
        fields=('name','email','phone','age','image','gender','religion','address')

firstapp/views.py
from django.shortcuts import render
from firstapp.forms import ProfileForm
from firstapp.models import Profile
from django.shortcuts import render,HttpResponseRedirect
from django.views.generic import View,TemplateView,ListView,DetailView,CreateView,UpdateView,DeleteView
from django.urls import reverse
from django.urls import reverse_lazy

# Create your views here.
def home(request):
    return render(request,'firstapp/index.html')

def profile(request):
    form=ProfileForm()
    registration=False
    if request.method=='POST':
        form=ProfileForm(request.POST,request.FILES)
        if form.is_valid():
            form.save()
            registration=True
            return HttpResponseRedirect(reverse('firstapp:home'))
    dict={'form':form,'registration':registration}
    return render(request,'firstapp/profile.html',context=dict)


class IndexView(ListView):
    context_object_name='student_list'
    model=Profile
    template_name='firstapp/index.html'

class StudentDetail(DetailView):
    context_object_name='students'
    model=Profile
    template_name='firstapp/student_details.html'

secondApp/views.py
from django.shortcuts import render

# Create your views here.

templates/base.html
<!DOCTYPE html>
{%load static%}
{%load crispy_forms_tags%}
<html lang="en">
<head>
  <title>{%block title_block%} All Students {%endblock%}</title>
  <meta charset="utf-8">


  <link rel="stylesheet" href="https://maxcdn.bootstrapcdn.com/bootstrap/4.5.2/css/bootstrap.min.css">
  <script src="https://code.jquery.com/jquery-3.5.1.slim.min.js"></script>
  <script src="https://cdn.jsdelivr.net/npm/@popperjs/core@2.9.1/dist/umd/popper.min.js"></script>
  <script src="https://maxcdn.bootstrapcdn.com/bootstrap/4.5.2/js/bootstrap.min.js"></script>
  <link  href="https://maxcdn.bootstrapcdn.com/font-awesome/4.7.0/css/font-awesome.min.css" rel="stylesheet">


</head>
<body>

<nav class="navbar navbar-expand-sm bg-dark navbar-dark">
  <div class="container-fluid">
    <ul class="navbar-nav">
      <li class="nav-item active">
        <a class="nav-link" href="{%url 'firstapp:home'%}">Home</a>
      </li>
     <!-- 
    <div class="nav-item dropdown">
      <a class="nav-link dropdown-toggle" href="#"  id="dropdownMenuLink" data-toggle="dropdown" >
       
      </a>
      <div class="dropdown-menu">
        <a class="dropdown-item" href="">Write Blog</a>
        <a class="dropdown-item" href="">My Blogs</a>
        <a class="dropdown-item" href="">Your Profile</a>
        <a class="dropdown-item" href="" >Logout</a>
      </div>
      
    </div>
    -->

    <li class="nav-item ">
      <a class="nav-link" href="{%url 'firstapp:profile'%}">Student Registration</a>
    </li>
 
  </div>

</ul>
</nav>
<div class="container" style="padding-top: 20px;">
{% block body_block %}

{% endblock %}

</div>



</body>
</html>

templates/firstapp/index.html
{% extends 'base.html'%}
{%block body_block%}
<h3>All Students</h3>
<ul>
    {%for student in student_list%}
    <li><a href="{% url 'firstapp:student_details' pk=student.pk %}">{{student.name}} </a></li>
    {%endfor%}
</ul>

{%endblock%}

templates/firstapp/profile.html
{% extends 'base.html'%}
{%load crispy_forms_tags%}
{%block title_block%}Sign Up {%endblock%}
{% block body_block %}
{%if registered%}
<div class="alert alert-success">
    Account Created Successfully !! <a href="">Login Here</a>
</div>
{%else%}

<h2>Create New Account </h2>
<form method="POST" enctype="multipart/form-data">
    {% csrf_token %}
    {{form|crispy}}
<button type="submit" class="btn btn-success btn-sm">Create Account</button>

</form>
<br>

<p> Already Have an Account ? <a href="">Login Here</a></p>
{%endif%}

{%endblock%}

templates/firstapp/signUp.html
{% extends 'base.html'%}
{%load crispy_forms_tags%}
{%block title_block%}Sign Up {%endblock%}
{% block body_block %}
{%if registered%}
<div class="alert alert-success">
    Account Created Successfully !! <a href="">Login Here</a>
</div>
{%else%}

<h2>Create New Account </h2>
<form method="POST">
    {% csrf_token %}
    {{form|crispy}}
<button type="submit" class="btn btn-success btn-sm">Create Account</button>

</form>
<br>

<p> Already Have an Account ? <a href="">Login Here</a></p>
{%endif%}

{%endblock%}

templates/firstapp/student_details.html
{% extends 'base.html'%}
{%block body_block%}

<h3>Student Details :</h3>
<p>Name : {{students.name}} </p>
<p>Gerder : {{students.gender}}</p>
<p>Address : {{students.address}}</p>
<p>Phone Number : {{students.phone}}</p>
<p>Email : {{students.email}}</p>
<img src="/media/{{students.image}}" class="rounded-circle" width="100px">

{%endblock%}